### ISSUE TITLE
`brew install aws` errors

### ISSUE THREAD

**Issue by mammykins** [ukgovdatascience/databox#35]
The README says do  `brew install aws`, it gives this error in the terminal.

<img width="640" alt="screen shot 2018-01-31 at 10 43 31" src="https://user-images.githubusercontent.com/6576226/35618779-da80b194-0673-11e8-8403-52caab53e524.png">

Do you mean `brew install awscli`?

**Comment by andreagrandi** [comment]
Hi @mammykins they may have changed the formula name in the mean time, but yes... `aws-cli` seems to be the right one. In any case I would also try a `brew update` first, just in case.

**Comment by davidread** [comment]
I'm pretty sure you're right, ```brew install awscli``` installs the ```aws``` cli tool referred to.
